version: "3"
networks:
  main:
    driver: bridge
services:
  app:
    build: .
    environment:
      - "HTTP_PORT=9090"
      - "GRPC_PORT=8080"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - main
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - main